### ISSUE TITLE
Error: i.draggable is not a function

### ISSUE THREAD

**Issue by nikomouk** [codef0rmer/angular-dragdrop#101]
Hello,

each time i'm trying to use your plugin, i got this error :"Error: i.draggable is not a function"
Any idea 

Thanks !

**Comment by dreamerkumar** [comment]
Only worked when they are included in the following sequence. Note jquery before jquery-ui. Both of them before angular. And then drag and drop after angular because this file has angular code in it.

`'public/lib/jquery/dist/jquery.min.js',`
`'public/lib/jquery-ui/jquery-ui.min.js',`
`'public/lib/angular/angular.js',`
`'public/lib/angular-dragdrop/src/angular-dragdrop.min.js',`

**Comment by skolade** [comment]
This is not working for me, getting same error!

**Comment by marciogurka** [comment]
I'm still getting this error and I'm importing in the correct order (JQuery, JQueryUI, Angular and Angular DragDrop) @codef0rmer
