### ISSUE TITLE
cannot make it work with ionic framework ?

### ISSUE THREAD

**Issue by firaskudsy** [codef0rmer/angular-dragdrop#218]
him am trying to implement the angular-dragdrop in my ionic framework app, but i cant get it work, any working sample or hints for implementing this into an ionic framework apps ?

Thanks

**Comment by privetr** [comment]
+1

**Comment by codef0rmer** [comment]
@firaskudsy: Can you be more specific about an error? Is it that drag-drop does not work or any JS error?

**Comment by privetr** [comment]
In my case, I had the following : 

At first I only installed bower package and included Js file as described :
I Had the following JS error : c.draggable is not a function

Then I saw that for devices compatibility we had to include jQuery-UI and touch-punch.js
After it, I didn't have JS errors anymore, until I Tried to drag a simple object : 
"Uncaught TypeError: Cannot read property 'msie' of undefined", coming from a.widget._mouseMove	@	jquery-ui-1.8.21.min.js:5

I hope it will help you, because I really would like to use this amazing plugin in my Ionic App :)

**Comment by codef0rmer** [comment]
Which version of jQuery are you using? Because `$.browser` is deprecated since jQuery 1.3 and is removed in 1.9. 
http://jquery.com/upgrade-guide/1.9/#jquery-browser-removed

Can you confirm if the issue persists by using jQuery < 1.9?

**Comment by privetr** [comment]
I was using jQuery 2.1
I tried with Jquery 1.8.3 and I Have the following error : 
Uncaught TypeError: a.curCSS is not a function :(

**Comment by privetr** [comment]
My mistake,
I tried to do a simple Codepen to show you errors, but your plugin works well this time :) 

http://codepen.io/privetr/pen/JYWppB

I will try to find out why it's not the same case in my bigger app.

**Comment by LucaTerzaghi** [comment]
+1 !!!!

**Comment by khullah** [comment]
Yes, I had the same error using Electron. The thing is AngularJs developers generally dont use jQuery directly anymore, nor UI, since it comes with jqLite already.

Just add jquery and jquery-ui in your index.html and you'll be fine.
