### ISSUE TITLE
element.draggable is not a function

### ISSUE THREAD

**Issue by aurigadl** [codef0rmer/angular-dragdrop#65]
some times the directives run before to charge the dom.
This makes the following error.

"Error: element.draggable is not a function
jqyoui</<.link/</</</updateDraggable@http://localhost:9000/libs-js-thirdparty/angular-dragdrop/src/angular-dragdrop.js

I am try to put  in the directive but this dont function.

$timeout(function(){})

and 

angular.element(document).ready(function(){})

Browser: firefox 28.xxx

**Comment by PsiOps** [comment]
This is still an issue for me. I don't use RequireJS, but simply declare the dependencies in my index.html. I declare JQuery and JQuery-Ui, both before loading the angular-dragdrop.js. I get this exact same error. This is the clone url of my repo in which the issue is reproducable: https://github.com/PsiOps/WfDAngular.git

**Comment by codef0rmer** [comment]
You have added jquery and jqueryui after angular.js. Change the order as:

```
<script src="app/scripts/jquery/jquery.min.js"></script>
<script src="app/scripts/jquery/jquery-ui.min.js"></script>
<script src="app/scripts/angular/1.4.0-beta.1/angular.min.js"></script>
```

**Comment by PsiOps** [comment]
Great, it worked! Thanks a lot for looking into this and spotting my rather
noob-ish mistake.

**Comment by pepBR** [comment]
Thanks codef0rmer, I guess this info should be in the readme file. I would never have it figured out by myself.

**Comment by Sandeep821** [comment]
I have right sequence but still getting same error 'TypeError: element.draggable is not a function'
