### ISSUE TITLE
Retrieving Target Scope

### ISSUE THREAD

**Issue by joseym** [codef0rmer/angular-dragdrop#87]
#74 was closed before confirmation so starting a new issue.

Based on the last comment

> $(event.target).scope() might be useful.

I can confirm that this is **A** scope, but probably not the scope assigned to the target via `ng-model`.

**Expected**

``` json
{
  _id: "5329f06c8b0acf020098c265",
  name: "Test File"
}
```

**Received**

``` log
Child {$id: "00P", this: Child, $$listeners: Object, $parent: Child, $$childTail: null…}
$$childHead: null
$$childTail: null
$$listeners: Object
$$nextSibling: Child
$$prevSibling: null
$$watchers: Array[3]
$id: "00P"
$parent: Child
dndDragItem: Object
parent: Object
this: Child
__proto__: Child
```

Both `dndDragItem` and `parent` contain the drag item model information, but I'm looking for the model of the drop.

I'm using DragDrop to "move" files around in my data, so essentially I need to know the ID of the drop zone so that I can assign it to the drag item as the parent id.

**Comment by JimmyBoh** [comment]
@codef0rmer I tried using `$(event.target).scope()` but it is saying `$(...).scope is not a function`. Any ideas?

**Comment by codef0rmer** [comment]
@JimmyBoh: try using `angular.element(event.target).scope()`.

**Comment by JimmyBoh** [comment]
Thanks @codef0rmer, that did the trick!

**Comment by swamywiz** [comment]
If you have debugInfoEnabled turned off looks like scope() on an angular element returns undefined. And we want to turn off the debugInfo in the production settings. 
So to work around this I had to assign HTML element id which is same as the object name or index and extract this in the onDrop callback as Event.target.id giving me the object.  But is there any better way of doing this rather than assuming that the template id matches object name?
